version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    container_name: nginx-local
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - goboards-network