"""create meetups

Revision ID: 982b66e9d34e
Revises: d7a0992fb0a7
Create Date: 2024-07-25 00:59:02.666151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982b66e9d34e'
down_revision: Union[str, None] = 'd7a0992fb0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetups',
    sa.Column('meetup_status', sa.Enum('NEW', 'DISCUSSION', 'CLOSED', 'FINISHED', name='meetupstatus'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('max_person_amount', sa.Integer(), nullable=False),
    sa.Column('meetup_date', sa.Date(), nullable=False),
    sa.Column('preferred_start_time', sa.Time(), nullable=False),
    sa.Column('preferred_end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetups_users',
    sa.Column('meetup_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_status', sa.Enum('INITIATOR', 'PARTICIPANT', name='usermeetupstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meetup_id', 'user_id', name='meetup_user_unique')
    )
    op.create_table('meetups_games',
    sa.Column('meetup_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meetup_id', 'game_id', name='meetup_game_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetups_games')
    op.drop_table('meetups_users')
    op.drop_table('meetups')
    # ### end Alembic commands ###
