"""update game table

Revision ID: d7a0992fb0a7
Revises: 12a86a612bbc
Create Date: 2024-07-20 13:24:55.956824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a0992fb0a7'
down_revision: Union[str, None] = '12a86a612bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'games', ['name'])
    op.create_foreign_key(None, 'games', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_column('games', 'user_id')
    # ### end Alembic commands ###
